POST http://localhost:8080/save/users
Content-Type: application/json

< ./users.json

###

GET http://localhost:8080/name?name=케이

###

GET http://localhost:8080/korean?korean=사과

###

GET http://localhost:8080/english?english=hi

###

POST http://localhost:8080/condition
Content-Type: application/json

< ./condition.json